### ISSUE TITLE
Update lamejs dependency

### ISSUE THREAD

**Issue by isolin** [cstoquer/audio-encoder#9]
Working with audio-encoder, I discovered an issue [as described here](https://github.com/zhuker/lamejs/issues/65#issuecomment-982054380). My colleague reported it and luckily the maintainer of [lamejs](https://www.npmjs.com/package/lamejs) package released a new version 1.2.1 to fix that.

It would be great if you could update the dependency to the most recent version (1.2.0 -> 1.2.1) so that I don't have to emulate the bugfix manually each time I build.

**Comment by isolin** [comment]
Update: Secondary [issues](https://github.com/zhuker/lamejs/issues/86) arouse in lame.js. It will be better to wait for 1.2.2 to fix that.

**Comment by isolin** [comment]
Besides the issues in [lame.js](https://github.com/zhuker/lamejs), I noticed the same type of issues with audio-encoder. I needed to add `var` in `encodeMp3.js` manually at lines 48, 49, 60 and 61 to flawlessly encode audio. It would be great if these could be updated for future compatibility. I created a [pull request](https://github.com/cstoquer/audio-encoder/pull/10) for that.

**Comment by cstoquer** [comment]
I updated lamejs version to `1.2.1` and published `audio-encoder` on npm with version `1.0.3`.
Once a new version of lamejs is released, please reopen this issue and I'll update again.

**Comment by isolin** [comment]
Thank you! Sorry for the second commit, it followed after this PR. I should have placed it in a different branch.
